name: stock_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: 6.0.0
  dio: ^5.4.3+1
  camera: ^0.10.5+9
  flutter_tflite: 1.0.1
  shared_preferences: ^2.2.3
  mobx: ^2.3.3+2
  image: ^3.2.0
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/stock_logo.png
    - assets/model.tflite